version: '3'

services:
    dev:
        build: .
        volumes:
          - .:/usr/src/service:cached
        working_dir: /usr/src/service
        command: npm run serve
        ports:
            - 8080:8080
